---
kind: pipeline
name: lint
workspace:
  path: /opt/ansible/roles/veselahouba.f5_ansible

steps:
  - name: Super Linter
    image: github/super-linter:v4
    environment:
      RUN_LOCAL: "true"
      DEFAULT_WORKSPACE: /opt/ansible/roles/veselahouba.f5_ansible
      # Using own ansible check
      VALIDATE_ANSIBLE: false
      # Sorry pal, maybe one day
      VALIDATE_PYTHON_BLACK: false
      VALIDATE_PYTHON_MYPY: false
      VALIDATE_PYTHON_PYLINT: false
      VALIDATE_PYTHON_FLAKE8: false
      VALIDATE_PYTHON_ISORT: false

  - name: Own linter
    image: veselahouba/molecule
    commands:
      - ansible-galaxy collection install https://f5-ansible.s3.amazonaws.com/collections/f5networks-f5_modules-devel.tar.gz
      - shellcheck_wrapper
      - yamllint .
      - ansible-lint

---
kind: pipeline
name: release
depends_on:
  - lint
trigger:
  event:
    - tag
steps:
  - name: Publish
    image: veselahouba/molecule
    environment:
      GALAXY_API_KEY:
        from_secret: GALAXY_API_KEY
    commands:
      - >
        ansible-galaxy role import --api-key $${GALAXY_API_KEY}
        $${DRONE_REPO_OWNER} $${DRONE_REPO_NAME}

  - name: Slack notification
    image: plugins/slack
    settings:
      webhook:
        from_secret: slack_webhook
      channel: ci-cd
      template: >
        {{#success build.status}}
          Publish for `{{build.tag}}` succeeded.
          {{build.link}}
        {{else}}
          Publish for `{{build.tag}}` failed.
          {{build.link}}
        {{/success}}
    when:
      status:
        - success
        - failure
