---
kind: pipeline
name: lint
workspace:
  path: /opt/ansible/roles/veselahouba.f5_ansible

steps:
  - name: Super Linter
    image: github/super-linter:latest
    environment:
      RUN_LOCAL: "true"
      DEFAULT_WORKSPACE: /opt/ansible/roles/veselahouba.f5_ansible
      # Using own ansible check
      VALIDATE_ANSIBLE: false
      # Sorry pal, maybe one day
      VALIDATE_PYTHON_BLACK: false
      VALIDATE_PYTHON_PYLINT: false
      VALIDATE_PYTHON_FLAKE8: false
      VALIDATE_PYTHON_ISORT: false

  - name: Own linter
    image: veselahouba/molecule
    commands:
      - ansible-galaxy collection install https://f5-ansible.s3.amazonaws.com/collections/f5networks-f5_modules-devel.tar.gz
      - shellcheck_wrapper
      - yamllint .
      - ansible-lint
