---
- name: Import ASM policy {{ policy.name }}
  bigip_asm_policy_import:
    provider: "{{ f5_provider }}"
    name: "{{ policy.name }}"
    source: "{{ policy.file }}"
    force: "{{ policy.force | default(false) }}"
    partition: "{{ policy.partition | default(omit) }}"
  notify: Save config
  delegate_to: localhost
  tags: f5_asm

- name: Activate ASM policy {{ policy.name }}
  bigip_asm_policy_manage:
    provider: "{{ f5_provider }}"
    name: "{{ policy.name }}"
    active: "{{ policy.active | default(false) }}"
    partition: "{{ policy.partition | default(omit) }}"
  notify: Save config
  delegate_to: localhost
  tags: f5_asm
