---
- name: Remove ASM policy {{ policy.name }}
  bigip_asm_policy_manage:
    provider: "{{ f5_provider }}"
    name: "{{ policy.name }}"
    partition: "{{ policy.partition | default(omit) }}"
    state: absent
  notify: Save config
  delegate_to: localhost
  tags: f5_asm
