---
- name: Import ASM policy
  bigip_asm_policy_import:
    provider: "{{ f5_provider }}"
    name: "{{ item.name }}"
    source: "{{ item.file }}"
    force: "{{ item.force | default(false) }}"
  with_items: "{{ f5_asm_policies_deploy_list }}"
  notify: Save config
  delegate_to: localhost
  tags: f5_asm
