---
- name: "Remove PEM certificate {{ cert.name }}"
  bigip_ssl_certificate:
    partition: "{{ item.partition | default(omit) }}"
    provider: "{{ f5_provider }}"
    name: "{{ cert.name }}"
    state: absent
  delegate_to: localhost
  tags: f5_certificates

- name: "Remove key for {{ cert.name }}"
  bigip_ssl_key:
    partition: "{{ item.partition | default(omit) }}"
    provider: "{{ f5_provider }}"
    name: "{{ cert.name }}"
    state: absent
  delegate_to: localhost
  tags: f5_certificates
