---
- name: "Manage PEM certificate {{ cert.name }}"
  bigip_ssl_certificate:
    partition: "{{ item.partition | default(omit) }}"
    provider: "{{ f5_provider }}"
    name: "{{ cert.name }}"
    content: "{{ lookup('file', cert.certfile) }}"
    state: "{{ cert.state | default('present') }}"
  delegate_to: localhost
  when: cert.certfile is defined
  tags: f5_certificates

- name: "Manage key for {{ cert.name }}"
  bigip_ssl_key:
    partition: "{{ item.partition | default(omit) }}"
    provider: "{{ f5_provider }}"
    name: "{{ cert.name }}"
    content: "{{ lookup('file', cert.keyfile) }}"
    state: "{{ cert.state | default('present') }}"
  delegate_to: localhost
  when: cert.keyfile is defined
  tags: f5_certificates
