---
- name: Deploy data groups
  bigip_data_group:
    provider: "{{ f5_provider }}"
    name: "{{ item.name }}"
    records_src: "{{ item.file|default(omit) }}"
    records: "{{ item.records|default(omit) }}"
    type: "{{ item.type|default(omit) }}"
    internal: "{{ item.internal | default(false) }}"
  with_items: "{{ f5_data_group_list }}"
  when: ( f5_partial_deploy is not defined ) or ( item.name in f5_partial_deploy )
  notify: Save config
  delegate_to: localhost
  tags:
    - f5_data-groups
    - f5_irules
