---
- name: Manage users
  include_tasks: users.yml
  when:
    - f5_users is defined
    - f5_users | length > 0
  tags: f5_users

- name: Manage f5_partitions
  bigip_partition:
    name: "{{ item.name }}"
    description: "{{ item.description | default('omit') }}"
    state: "{{ item.state | default('present') }}"
    provider: "{{ f5_provider }}"
  with_items: "{{ f5_partitions }}"
  delegate_to: localhost
  tags: f5_partitions

- name: Deploy data groups
  include_tasks: data_groups.yml
  when:
    - f5_data_group_list is defined
    - f5_data_group_list | length > 0
  tags:
    - f5_data-groups
    - f5_irules

- name: Deploy iRules
  include_tasks: iRules.yml
  when:
    - f5_iRules_list is defined
    - f5_iRules_list | length > 0
  tags: f5_irules

- name: Fetch ASM policies
  include_tasks: asm_policies_fetch.yml
  when:
    - f5_asm_policies_fetch_list is defined
    - f5_asm_policies_fetch_list | length > 0
  tags: f5_asm

- name: Deploy ASM policies
  include_tasks: asm_policies_deploy.yml
  vars:
    policy: "{{ item }}"
  with_items: "{{ f5_asm_policies_deploy_list }}"
  when:
    - item.state | default('present') == 'present'
    - ( f5_partial_deploy is not defined ) or ( item.name in f5_partial_deploy )
  tags: f5_asm

- name: Deploy cetificates
  include_tasks: certificates.yml
  vars:
    cert: "{{ item }}"
  with_items: "{{ f5_certificates_list }}"
  when:
    - item.name is defined
    - ( f5_partial_deploy is not defined ) or ( item.name in f5_partial_deploy )
  tags: f5_certificates
  no_log: true

- name: Deploy profiles
  include_tasks: profiles.yml
  vars:
    profile: "{{ item }}"
  with_items: "{{ f5_profiles_list }}"
  when:
    - item.name is defined
    - ( f5_partial_deploy is not defined ) or ( item.name in f5_partial_deploy )
  tags: f5_profiles
  no_log: true

- name: Configure pools, members, virtual servers
  include_tasks: ltm.yml
  when: ( (f5_pools is defined) and (f5_pools | length > 0) )
    or ( (f5_pool_members is defined) and (f5_pool_members | length > 0) )
    or ( (f5_virtual_servers is defined) and (f5_virtual_servers | length > 0) )
  tags: f5_ltm

- name: Deploy iApps
  include_tasks: iApps.yml
  when:
    (( f5_iApps_templates is defined ) and ( f5_iApps_templates | length > 0 )) or
    (( f5_iApps_services is defined ) and ( f5_iApps_services | length > 0 ))
  tags: f5_iapps

- name: Undeploy ASM policies
  include_tasks: asm_policies_undeploy.yml
  vars:
    policy: "{{ item }}"
  with_items: "{{ f5_asm_policies_deploy_list }}"
  when:
    - item.state | default('present') == 'absent'
    - ( f5_partial_deploy is not defined ) or ( item.name in f5_partial_deploy )
  tags: f5_asm
