---
- name: Manage users
  bigip_user:
    username_credential: "{{ item.username }}"
    password_credential: "{{ item.password }}"
    full_name: "{{ item.full_name }}"
    update_password: "{{ item.update_password | default('always') }}"
    partition_access: "{{ item.partition_access }}"
    state: "{{ item.state | default('present') }}"
    provider: "{{ f5_provider }}"
  delegate_to: localhost
  with_items: "{{ f5_users }}"
  when: ( f5_partial_deploy is not defined ) or ( item.username in f5_partial_deploy )
  tags: f5_users
  loop_control:
    label: "{{ item.username }} | {{ item.state|default('present') }}"
